version: '3'
services:
 # Php-fpm configuration
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "../.././app/html:/var/www/html"
      - "./config/php.ini:/usr/local/etc/php/php.ini"

  
