version: '3'
services:
 # Nginx server configuration   
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .././app/html:/var/www/html
      - ./sites-available/site.conf:/etc/nginx/sites-available/site.conf
    ports:
      - "8003:80"
    networks:
      - nginx
      
networks:
  nginx:
    name: nginx