version: '3'
services:
 # Nginx server configuration   
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .././app/html:/var/www/html
      - ./sites-available/site.conf:/etc/nginx/sites-available/site.conf
    ports:
      - "8015:80"
    networks:
      - nginxx
      
networks:
  nginxx:
    name: nginxx