version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:1.23.2-alpine
    volumes:
      - .././app/html:/var/www/html
      - ./sites-available:/etc/nginx/conf.d/
    ports:
      - "8003:80"
    networks:
      - nginx
      
networks:
  nginx:
    name: nginx