version: '3'
services:
 # Nginx server configuration   
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .././app/html:/var/www/html
      - ./sites-available/site.conf:/etc/nginx/sites-available/site.conf
    ports:
      - "8015:80"
    networks:
        nginx_static:
          ipv4_address: 192.168.78.10
      
networks:
  # nginxx:
  #   name: nginxx
  nginx_static:
     name: nginx_static
     ipam:
      driver: default
      config:
        - subnet: "192.168.78.1/24"
