version: '3'
services:
 # Mysql configuration
  mariadb:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
        - MYSQL_DATABASE=vtiger_db
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_USER=vtiger_user
        - MYSQL_PASSWORD=vtiger_user@123
    ports:
        - "3324:3306"
    volumes:
        - "parsvtt_mariadb:/var/lib/mysql" 
    networks:
      - mariadbb

volumes:
  parsvtt_mariadb:
    name: parsvtt_mariadb
networks:
  mariadbb:
    name: mariadbb

  
